# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: get_stock.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'get_stock.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fget_stock.proto\"!\n\x0fGetStockRequest\x12\x0e\n\x06ticker\x18\x01 \x01(\t\"z\n\x10GetStockResponse\x12\x34\n\nstock_data\x18\x01 \x03(\x0b\x32 .GetStockResponse.StockDataEntry\x1a\x30\n\x0eStockDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\x32H\n\x0fGetStockService\x12\x35\n\x0cGetStockData\x12\x10.GetStockRequest\x1a\x11.GetStockResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'get_stock_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETSTOCKRESPONSE_STOCKDATAENTRY']._loaded_options = None
  _globals['_GETSTOCKRESPONSE_STOCKDATAENTRY']._serialized_options = b'8\001'
  _globals['_GETSTOCKREQUEST']._serialized_start=19
  _globals['_GETSTOCKREQUEST']._serialized_end=52
  _globals['_GETSTOCKRESPONSE']._serialized_start=54
  _globals['_GETSTOCKRESPONSE']._serialized_end=176
  _globals['_GETSTOCKRESPONSE_STOCKDATAENTRY']._serialized_start=128
  _globals['_GETSTOCKRESPONSE_STOCKDATAENTRY']._serialized_end=176
  _globals['_GETSTOCKSERVICE']._serialized_start=178
  _globals['_GETSTOCKSERVICE']._serialized_end=250
# @@protoc_insertion_point(module_scope)
